lesson8/admins/urls.py
from django.urls import path

from admins.views import IndexTemplateView, UserCreateView, UserUpdateView, UserDeleteView, UserListView, \
    CategoryListView, CategoryDeleteView, CategoryUpdateView, ProductListView, CategoryCreateView, ProductCreateView, \
    ProductUpdateView, ProductDeleteView

app_name = 'admins'
urlpatterns = [

    path('', IndexTemplateView.as_view(),name='index'),
    path('users/', UserListView.as_view(),name='admin_users'),
    path('users-create/', UserCreateView.as_view(),name='admin_users_create'),
    path('users-update/<int:pk>', UserUpdateView.as_view(),name='admin_users_update'),
    path('users-delete/<int:pk>', UserDeleteView.as_view(),name='admin_users_delete'),

    path('category/', CategoryListView.as_view(), name='admin_category'),
    path('category/create/', CategoryCreateView.as_view(), name='admin_category_create'),
    path('category-delete/<int:pk>/', CategoryDeleteView.as_view(), name='admin_category_delete'),
    path('category-update/<int:pk>/', CategoryUpdateView.as_view(), name='admin_category_update'),
    # path('category-detail/<int:pk>/', CategoryDetailView.as_view(), name='admin_category_detail'),

    path('product/', ProductListView.as_view(), name='admin_product'),
    path('product/create/', ProductCreateView.as_view(), name='admin_product_create'),
    path('product-update/<int:pk>/', ProductUpdateView.as_view(), name='admin_product_update'),
    path('product-delete/<int:pk>/', ProductDeleteView.as_view(), name='admin_product_delete'),
]

lesson8/authapp/urls.py
from django.urls import path
# from authapp.views import
from authapp.views import login,register,logout,profile

app_name = 'authapp'
urlpatterns = [

    path('login/', login,name='login'),
    path('register/', register,name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

lesson8/geekshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index,products

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index,name='index'),
    path('products/', include('mainapp.urls',namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),


]

urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

lesson8/admins/templates/admins/admin-category-create.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание категории</h1>
                <form action="{% url 'admins:admin_category_create' %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                                {{ form.name }}
                            </div>
                        </div>

                    </div>
                    <div class="form-row">

                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

lesson8/admins/templates/admins/admin-category-read.html
{% extends 'admins/base.html' %}

{% block content %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{ title }}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Категории
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Наименование</th>
                                    <th>Описание</th>
                                    <th>Активный</th>
                                    <th>Удалить</th>
                                    <th>Изменить</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Наименование</th>
                                    <th>Описание</th>
                                    <th>Активный</th>
                                    <th>Удалить</th>
                                    <th>Изменить</th>
                                </tr>
                                </tfoot>
                                <tbody>

                                {% for category in object_list %}
                                    <tr>
                                        <td>{{ category.name }}</td>
                                        <td>{{ category.description }}</td>
                                        <td class="text-center">
                                            {% if category.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}

                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <form action="{% url 'admins:admin_category_delete' category.id %}" method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                                            </form>
                                        </td>
                                        <td>
                                            <a href="{% url 'admins:admin_category_update' category.id %}">
                                                <input class="btn btn-success btn-block" type="submit" value="Изменить">
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_category_create' %}">
                            <button class="btn btn-success">Создать категорию</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>

{% endblock %}

lesson8/admins/templates/admins/admin-category-update-delete.html
{% extends 'admins/base.html' %}


{% block content %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование категории | {{ productcategory.name }}  </h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_category_update' productcategory.id %}" method="post">

                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование</label>
                                    {{ form.name }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                    {{ form.description }}
                                </div>
                            </div>
                        </div>


                        <div class="form-row">
                            <div class="col-lg-6" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>

{% endblock %}

lesson8/admins/templates/admins/admin-product-create.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание товара</h1>
                <form action="{% url 'admins:admin_product_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for=" {{ form.first_name.id_for_label }}">Название</label>
                               {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                  {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-5">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Цена</label>
                           {{ form.price }}
                        </div>
                        <div class="col-lg-5">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Колличество
                                почты</label>
                            {{ form.quantity }}
                        </div>
                        <div class="col-lg-2">
                            <label class="small mb-1" for="{{ form.age.id_for_label }}">Категория</label>
                            {{ form.category }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

lesson8/admins/templates/admins/admin-product-read.html
{% extends 'admins/base.html' %}

{% block content %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">{{ title }}</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Продукта
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Наименование</th>
                                    <th>Описание</th>
                                    <th>Цена</th>
                                    <th>Колличество</th>
                                    <th>Категория</th>
                                    <th>Удалить</th>
                                    <th>Изменить</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Наименование</th>
                                    <th>Описание</th>
                                    <th>Цена</th>
                                    <th>Колличество</th>
                                    <th>Категория</th>
                                    <th>Удалить</th>
                                    <th>Изменить</th>
                                </tr>
                                </tfoot>
                                <tbody>

                                {% for product in object_list %}
                                    <tr>
                                        <td>{{ product.name }}</td>
                                        <td>{{ product.description }}</td>
                                        <td>{{ product.price }}</td>
                                        <td>{{ product.quantity }}</td>
                                        <td>{{ product.category }}</td>
                                        <td>
                                            <form action="{% url 'admins:admin_product_delete' product.id %}" method="post">
                                                {% csrf_token %}
                                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                                            </form>
                                        </td>
                                        <td>
                                            <a href="{% url 'admins:admin_product_update' product.id %}">
                                                <input class="btn btn-success btn-block" type="submit" value="Изменить">
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_product_create' %}">
                            <button class="btn btn-success">Создать продукта</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>

{% endblock %}

lesson8/admins/templates/admins/admin-product-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование товара | {{ product.name }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_product_update' product.id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Название товара</label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание товара</label>
                                    {{ form.description }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{ form.image }}
                                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                        изображение</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.price.id_for_label }}">Имя
                                    цена</label>
                                {{ form.price }}
                            </div>
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Колличество</label>
                                {{ form.quantity }}
                            </div>
                            <div class="col-lg-2">
                                <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                                {{ form.category }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <form action="{% url 'admins:admin_product_delete' product.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>

{% endblock %}

lesson8/admins/templates/admins/admin-users-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Пользователи</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Пользователи
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for user in object_list %}
                                    <tr>
                                        <td><a href="{% url 'admins:admin_users_update' user.id %}"
                                               style="color: dodgerblue">{{ user.username }}</a></td>
                                        <td>{{ user.first_name }}</td>
                                        <td>{{ user.last_name }}</td>
                                        <td>{{ user.email }}</td>
                                        <td class="text-center">
                                            {% if user.is_staff %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}

                                        </td>


                                        <td class="text-center">

                                            {% if user.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_users_create' %}">
                            <button class="btn btn-success">Создать пользователя</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

lesson8/admins/templates/admins/admin-users-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}

    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_users_update' user.id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                    {{ form.first_name }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                    {{ form.last_name }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{ form.image }}
                                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                        изображение</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя
                                    пользователя</label>
                                {{ form.username }}
                            </div>
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                    почты</label>
                                {{ form.email }}
                            </div>
                            <div class="col-lg-2">
                                <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                                {{ form.age }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                        </div>
                    </form>
                    <form action="{% url 'admins:admin_users_delete' user.id %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12" style="margin-top: 33px;">
                                <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>

{% endblock %}

lesson8/admins/templates/admins/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>GeekShop - Admin</title>
    <link href="{% static  'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="admin.html">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'authapp:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    {% include 'admins/includes/siberia_bar.html' %}
    {% block content %}
    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static  'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static  'js/datatable.js' %}"></script>
</body>
</html>